orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
version: 2.1
workflows:
  install_and_configure_cli:
    jobs:
      - gcp-cli/install_and_initialize_cli:
          executor: gcp-cli/default
          steps:
            - run: gcloud ai-platform jobs list
