version: 2.1
orbs:
  jq: circleci/jq@1.9.0
  gcp-cli: circleci/gcp-cli@1.8.4
jobs:
  setup-environment:
    docker:
      - image: circleci/python:3.7.9
    working_directory: ~/circleci-ai-platform-example
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            poetry install
            poetry config --list

  trigger-training-job:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/circleci-ai-platform-example
    steps:
      - checkout
      - jq/install
      - gcp-cli/install
      - gcp-cli/initialize
      - run: |
          gcloud --version

      - run:
          name: submit training jobs
          command: |
            TIMESTAMP=`date "+%Y%m%d_%H%M%S"`
            JOB_NAME=christineoo_${TIMESTAMP}
            echo ${TIMESTAMP}
            echo ${JOB_ID}
            make gcs_bucket_name=${GCS_BUCKET_NAME} job_name=${JOB_NAME} submit_job
            bash scripts/job_status.sh ${GOOGLE_PROJECT_ID} ${JOB_NAME}

workflows:
  build:
    jobs:
      - setup-environment:
        filters:
          branches:
            only: /ai-platform\/.*
      - trigger-training-job:
          requires:
            - setup-environment
          filters:
            branches:
              only: /ai-platform\/.*/
